changesDir: .changes
unreleasedDir: unreleased
headerPath: header.tpl.md
versionHeaderPath: ""
versionFooterPath: ""
changelogPath: CHANGELOG.md
versionExt: md
versionFormat: '## {{.Version}} - {{.Time.Format "2006-01-02"}}'
kindFormat: '### {{.Kind}}'
changeFormat: '* {{.Body}}'
headerFormat: ""
footerFormat: ""
kinds:
- label: Added
- label: Changed
- label: Deprecated
- label: Removed
- label: Fixed
- label: Security
custom:
- key: Field 1
  label: String Field
  type: string
- key: Field 2
  label: Int Field
  type: int
- key: Field 3
  label: Enum Field
  type: enum
  enumOptions: ["a", "b"]
