name: Check Skipping Steps

on:
  workflow_dispatch:

defaults:
  run:
    shell: bash

permissions: read-all

jobs:
  skip-all-steps:
    permissions: read-all
    uses: ./.github/workflows/workflow_skips.yml

  echo-line:
    name: "Check for changelog entry in cli"
    runs-on: ubuntu-latest
    needs: skip-all-steps
    steps:
      - run: echo "running"
