name: Check Changelog Entry

on:
  workflow_dispatch:

defaults:
  run:
    shell: bash

permissions: read-all

jobs:
  check_changes:
    permissions: read-all
    uses: ./.github/workflows/workflow_skips.yml

  cli-changelog:
    name: "Check for changelog entry in cli"
    runs-on: ubuntu-latest
    needs: check_changes
    steps:
      - run: echo "running"
