name: Changie Master Action

on:
  pull_request:
    # catch when the PR is opened with the label or when the label is added
    types: [opened, labeled]

permissions:
  contents: write
  pull-requests: read

jobs:
  dependency_changelog:
    runs-on: ubuntu-latest
    name: a job to add a changelog yaml file to this PR

    steps:
    
    - name: Create Changelog Commit on PR
      id: filename_time
      uses: emmyoop/changie_bot@main
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # could be ${{ secrets.EMMYOOP_BOT }}
        commit_author_name: "emmyoop bot"
        commit_author_email: "<emilyhayne@gmail.com>"
        commit_message: "My custom commit message"
        changie_kind: "Bug"
        label: "my_custom"
        custom_changelog_string: "custom:\n  Field 1: Some String\n  Field 2: 1\n  Field 3: a\n"