# **what?**
# Label a PR with a `community` label when a PR is opened by a user outside core/adapters

# **why?**
# To streamline triage and ensure that community contributions are recognized and prioritized

# **when?**
# When a PR is opened, not in draft or moved from draft to ready for review


name: Label community PRs

on:
  pull_request:
    types: [opened, ready_for_review]

defaults:
  run:
    shell: bash

permissions:
    pull-requests: write # labels PRs

jobs:
  open_issues:
    # If this PR already has the community label, no need to relabel it
    # If this PR is opened as draft, no need to label it
    if: |
      (!contains(github.event.pull_request.labels.*.name, 'community') &&
      (github.event.action == 'opened' && github.event.pull_request.draft == false ))
    uses: dbt-labs/actions/.github/workflows/label-community.yml@main
    with:
        github_team: "core"
        label: 'community'
    secrets: inherit
