# Test flow of skipped jobs with dependencies

name: Test Conditionals

on:
  workflow_dispatch:


jobs:
  job1:
    name: Job 1
    runs-on: ubuntu-latest
    steps:
      - name: Echo Job 1
        run: |
          echo Job 1

  skipped-job:
    # always skip!
    if: ${{ github.event_name == 'workflow_dispatch'}}
    name: Skipped Job
    needs:
      - job1
    steps:
      - name: Echo Job 2
        run: |
          echo Job 2

  job3:
    name: Job 3
    runs-on: ubuntu-latest
    needs:
      - job1
    steps:
      - name: Echo Job 3
        run: |
          echo Job 3
  

  job4:
    name: Job 4
    runs-on: ubuntu-latest
    needs:
      - job1
    steps:
      - name: Echo Job 4
        run: |
          echo Job 4


  job5:
    if: ${{ always() && (needs.skipped-job.result == 'success' || needs.skipped-job.result == 'skipped') && (needs.job4.result == 'success') && (needs.job3.result == 'success') }}
    name: Job 5
    runs-on: ubuntu-latest
    needs:
      - job4
      - skipped-job
      - job3
    steps:
      - name: Echo Job 5
        run: |
          echo Job 5

  job6:
    name: Job 6
    runs-on: ubuntu-latest
    needs:
      - job5
    steps:
      - name: Echo Job 6
        run: |
          echo Job 6

  job7:
    name: Job 7
    runs-on: ubuntu-latest
    needs:
      - job6
      - job5
    steps:
      - name: Echo Job 7
        run: |
          echo Job 7
