# Test flow of skipped jobs with dependencies

name: Test Conditionals

on:
  workflow_dispatch:


jobs:
  job1:
    name: Job 1
    runs-on: ubuntu-latest
    steps:
      - name: Echo Job 1
        run: |
          echo Job 1

  skipped-job:
    # always skip!
    if: ${{ github.event_name != 'workflow_dispatch'}}
    name: Skipped Job
    runs-on: ubuntu-latest
    needs:
      - job1
    steps:
      - name: Echo Job 2
        run: |
          echo Job 2

  job3:
    name: Job 3
    runs-on: ubuntu-latest
    needs:
      - job1
    steps:
      - name: Echo Job 3
        run: |
          echo Job 3

  conditional-job:
    if: ${{ always() && (needs.skipped-job.result == 'success' || needs.skipped-job.result == 'skipped') && (needs.job4.result == 'success') && (needs.job3.result == 'success') }}
    name: Conditional Job
    runs-on: ubuntu-latest
    needs:
      - skipped-job
      - job3
    steps:
      - name: Echo Job 5
        run: |
          echo Job 5

  job6:
    name: "Job 6 with always()"
    if: ${{ always() }}
    runs-on: ubuntu-latest
    needs:
      - conditional-job
    steps:
      - name: Echo Job 6
        run: |
          echo Job 6

  job7:
    name: "Job 7 with always()"
    if: ${{ always() }}
    runs-on: ubuntu-latest
    needs:
      - job6
      - conditional-job
    steps:
      - name: Echo Job 7
        run: |
          echo Job 7

  job8:
    name: "Job 8 no always()"
    runs-on: ubuntu-latest
    needs:
      - job6
      - conditional-job
    steps:
      - name: Echo Job 8
        run: |
          echo Job 8

  job9:
    name: "Job 9 always() only job6"
    if: ${{ always() }}
    runs-on: ubuntu-latest
    needs:
      - job6
    steps:
      - name: Echo Job 9
        run: |
          echo Job 9

  job10:
    name: "Job 10 no always() only job6"
    runs-on: ubuntu-latest
    needs:
      - job6
    steps:
      - name: Echo Job 10
        run: |
          echo Job 10

  job11:
    name: "Job 11 no always() only job9"
    runs-on: ubuntu-latest
    needs:
      - job9
    steps:
      - name: Echo Job 11
        run: |
          echo Job 11

  job12:
    name: "Job 12 no always() only job11"
    runs-on: ubuntu-latest
    needs:
      - job11
    steps:
      - name: Echo Job 11
        run: |
          echo Job 11
