# **what?**
# Release workflow provides the following steps:
# - checkout the given commit;
# - validate version in sources and changelog file for given version;
# - bump the version and generate a changelog if needed;
# - merge all changes to the target branch if needed;
# - run unit and integration tests against given commit;
# - build and package that SHA;
# - release it to GitHub and PyPI with that specific build;
#
# **why?**
# Ensure an automated and tested release process
#
# **when?**
# This workflow can be run manually on demand or can be called by other workflows

name: Release to GitHub and PyPI

on:
  workflow_dispatch:
    inputs:
      sha:
        description: "The last commit sha in the release"
        type: string
        required: true
      target_branch:
        description: "The branch to release from"
        type: string
        required: true
      version_number:
        description: "The release version number (i.e. 1.0.0b1)"
        type: string
        required: true
      build_script_path:
        description: "Build script path"
        type: string
        default: "scripts/build-dist.sh"
        required: true
      env_setup_script_path:
        description: "Environment setup script path"
        type: string
        default: "scripts/env-setup.sh"
        required: false
      s3_bucket_name:
        description: "AWS S3 bucket name"
        type: string
        default: "core-team-artifacts"
        required: true
      package_test_command:
        description: "Package test command"
        type: string
        default: "dbt --version"
        required: true
      test_run:
        description: "Test run (Publish release as draft)"
        type: boolean
        default: true
        required: false
      nightly_release:
        description: "Nightly release to dev environment"
        type: boolean
        default: false
        required: false
  workflow_call:
    inputs:
      sha:
        description: "The commit sha for the release"
        type: string
        required: true
      version_number:
        description: "The release version number (i.e. 1.0.0b1)"
        type: string
        required: true
      changelog_path:
        description: "Path to changelog file"
        type: string
        default: ".changes/1.6.0.md"
        required: true
      test_run:
        description: "Test run (Publish release as draft)"
        type: boolean
        default: false
        required: false


permissions:
  contents: write # this is the permission that allows creating a new release

defaults:
  run:
    shell: bash

jobs:
  log-inputs:
    name: Log Inputs
    runs-on: ubuntu-latest
    steps:
      - name: "[DEBUG] Print Variables"
        run: |
          echo The last commit sha in the release: ${{ inputs.sha }}
          echo The release version number:         ${{ inputs.version_number }}
          echo Changelog path:                     ${{ inputs.changelog_path }}
          echo Test Run:                           ${{ inputs.test_run }}

  generate-fake-artifact:
    name: Generate fake artifact to release
    runs-on: ubuntu-latest

    steps:
      - name: "Create dummy changelog"
        run: |
          echo "This is the fancy changelog!" > ${{ inputs.changelog_path}}

      - name: "Create dummy artifact"
        run: |
          echo "This is the atrifact!" > dist/my_artifact.txt

      - name: "Upload Build Artifact - ${{ inputs.version_number }}"
        uses: actions/upload-artifact@v3
        with:
            name: ${{ inputs.version_number }}
            path: |
                ${{ inputs.changelog_path }}
                ./dist/
                !dist/dbt-${{ inputs.version_number }}.tar.gz
            retention-days:  5

  github-release:
    name: GitHub Release
    needs: [generate-fake-artifact]

    uses: dbt-labs/dbt-release/.github/workflows/github-release.yml@er/track-latest

    with:
      sha: ${{ inputs.sha }}
      version_number: ${{ inputs.version_number }}
      changelog_path: ${{ inputs.changelog_path }}
      test_run: ${{ inputs.test_run }}


