# **what?**
# Open an issue in docs.getdbt.com when a PR is labeled `user docs`

# **why?**
# To reduce barriers for keeping docs up to date

# **when?**
# When a PR is labeled `user docs` and is merged.  Runs on pull_request_target to run off the workflow already merged,
# not the workflow that existed on the PR branch.  This allows old PRs to get comments.


name: Open issues in docs.getdbt.com repo when a PR is labeled
run-name: "Open an issue in docs.getdbt.com for PR #${{ github.event.pull_request.number }}"

on:
  issues:
    types: [labeled, closed]

defaults:
  run:
    shell: bash

permissions:
    issues: write # opens new issues
    pull-requests: write # comments on PRs


jobs:
  open_issues:
    runs-on: ubuntu-latest
    steps:
      - name: "Is the issue open?"
        id: is_open
        run: |
          echo ${{ github.event.issue.closed }}
          echo ${{ github.event.issue.open }}
