

name: Output Issue Metadata

on:
  issues:
    types: [labeled, closed]
  pull_request_target:
    types: [labeled, closed]

defaults:
  run:
    shell: bash

permissions:
    issues: read # opens new issues


jobs:
  open_issues:
    runs-on: ubuntu-latest
    steps:
      - name: "Is the issue open?"
        id: is_open
        run: |
          echo ${{ github.event.issue.state }}
          echo ${{ github.event.issue.number }}
          echo ${{ github.event.issue.state_reason }}
          echo ${{ github.event.issue.comments }}
      - name: "Is the issue open?"
        run: |
          echo ${{ github.event.issue.pr.number }}
          echo ${{ github.event.pull_request.number }}
      - name: "Pick one"
        run: |
          echo ${{ github.event.pull_request.number || github.event.issue.number }}
