
name: Test Triggering a Workflow With labels
run-name: "Testing for PR #${{ github.event.pull_request.number }}"

on:
  pull_request_target:
    types: [labeled, closed]

defaults:
  run:
    shell: bash

permissions:
    all: read


jobs:
  open_issues:
    if: (contains( github.event.pull_request.labels.*.name, 'user docs') && github.event.pull_request.merged == true) || (github.event.label.name == 'user docs' && github.event.pull_request.labeled == true )
    runs-on: ubuntu-latest
    steps:
      - name: Echo the labels
        run: |
            echo "All the labels are: ${{ github.event.pull_request.labels.*.name }}"
            echo "The event label is: ${{ github.event.pull_request.label.name }}"
