
name: Test Triggering a Workflow With labels
run-name: "Testing for PR #${{ github.event.pull_request.number }}"

on:
  pull_request_target:
    types: [labeled, closed]

defaults:
  run:
    shell: bash

permissions: read-all


jobs:

  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Echo the labels
        run: |
            echo "All the labels are: ${{ github.event.pull_request.labels}}"
            echo "The event label is: ${{ github.event.label.name }}"
      - name: A different way to print labels
        if: github.event.label.name == 'user docs'
        run: |
          echo "the label was added"
          echo "event name is:" ${{ github.event_name }} 
          echo "event type is:" ${{ github.event.action }} 

  conditional_labels:
    if: |
      (github.event.pull_request.merged == true) &&
      ((github.event.action == 'closed' && contains( github.event.pull_request.labels.*.name, 'user docs')) || 
      (github.event.action == 'labeled' && github.event.label.name == 'user docs'))
    runs-on: ubuntu-latest
    steps:
      - name: Echo the labels
        run: |
            echo "The PR is merged: ${{ github.event.pull_request.merged }}"
            echo "The event label is: ${{ github.event.label.name }}"
  
  minor_conditional_labels:
    if: ${{ contains(github.event.pull_request.label.name, 'special label') }}
    runs-on: ubuntu-latest
    steps:
      - name: Echo the labels
        run: |
            echo "Triggered by the special label"
  
  minor_conditional_labels_retrigger:
    if: ${{ contains(github.event.pull_request.labels.*.name, 'special label') }}
    runs-on: ubuntu-latest
    steps:
      - name: Echo the labels
        run: |
            echo "Triggered by any label"
