name: Playground for Workflow Testing

on:
  workflow_dispatch:
    inputs:
      sha:
       description: 'The last commit sha in the release'
       required: true
      version_number:
       description: 'The release version number (i.e. 1.0.0b1)'
       required: true
       default: 2.2.2

defaults:
  run:
    shell: bash

jobs:

  get_release_by_tag:
    name: Test GH CLI find release by tag
    runs-on: ubuntu-latest

    steps:
      - name: Find Release by tag
        id: cli_tag
        run: |
          release_commit=`gh release view v${{ inputs.version_number }} --json targetCommitish`
          echo "::set-output name=releaseJson::$release_commit"

  get_release_by_commit:
    name: Test GH CLI find by commit
    runs-on: ubuntu-latest

    steps:
      - name: Find Release by tag
        id: cli_tag
        run: |
          release_commit=`gh release view v${{ inputs.version_number }} --json targetCommitish`
          echo "::set-output name=releaseJson::$release_commit"

  create_release:
    name: Test GH CLI Release Creation
    runs-on: ubuntu-latest

    steps:
      - name: Find Release by tag
        id: cli_tag
        run: |
          VERSION=v${{ version_number }}
          CHANGELOG_FILE=CHANGELOG.md
          TITLE="my_repo v1.2.3"
          PRERELEASE=''
          gh release create $VERSION -t $TITLE -F $CHANGELOG_FILE --target ${{ input.sha }} $PRERELEASE
          gh release create v1.2.3 -t "my_repo v1.2.3" -F CHANGELOG.md --target ${{ input.sha }} ''