name: "Return Team Membership"

on:
  workflow_dispatch:

permissions: read-all


jobs:
  job_1:
    runs-on: ubuntu-latest

    steps:
      - name: Get team membership
        uses: actions/github-script@v6
        id: team-membership
        with:
          script: |
            curl \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"\
              -H "X-GitHub-Api-Version: 2022-11-28" \
              https://api.github.com/orgs/$ORG/teams/$TEAM_SLUG/members
        env:
          ORG: rockmans
          TEAM: core

      - name: Get result
        run: echo "${{steps.team-membership.outputs.result}}"
