name: "Return Team Membership"

on:
  workflow_dispatch:

permissions: read-all

env:
  ORG: rockmans
  TEAM: core


jobs:
  job_1:
    runs-on: ubuntu-latest

    steps:
      - name: Set Core Team Membership for Changie Contributors exclusion
        run: |
          response="$(gh api -H 'Accept: application/vnd.github+json' /orgs/$ORG/teams/$TEAM/members)"
          echo $response
          echo $ORG
          echo $TEAM
          echo 'CHANGIE_CORE_TEAM=?' >> $GITHUB_ENV
        env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
