name: Update Triage Label Internal

on: issue_comment

defaults:
  run:
    shell: bash

permissions:
  issues: write

jobs:
  triage_label:
    uses: dbt-labs/actions/.github/workflows/swap-labels.yml@er/add-labeler
    with:
      add_label: "triage"
      remove_label: "awaiting_response"
    secrets: inherit # this is only acceptable because we own the action we're calling