name: Update Triage Label Internal

on: issue_comment

defaults:
  run:
    shell: bash

permissions:
  issues: write

jobs:
  triage_label:
    uses: dbt-labs/actions/.github/workflows/replace-label.yml@main
    with:
      original_label: "awaiting_response"
      new_label: "triage"
    secrets: inherit