

name: How do working dirs work

on:
    workflow_dispatch:


jobs:
    update-branches:
        runs-on: ubuntu-latest

        steps:
            - name: "Checkout repository"
              uses: actions/checkout@v4

            - name: "Set up Python"
              uses: actions/setup-python@v5
              with:
                python-version: "${{ env.PYTHON_VERSION }}"

            - name: "ls"
              run: |
                ls

            - name: "ls"
              run: |
                ls
              working-directory: scripts

            - name: "ls"
              run: |
                ls
              working-directory: ./scripts

            - name: "Run script"
              run: |
                ./printing.py
              working-directory: ./scripts
            
            - name: "Run script"
              run: |
                ./printing.py
              working-directory: scripts
