# used to call other workflows in testing


name: "Testing Workflow Call"

on:
  schedule:
    - cron: "* * * * *" # run every minute
  workflow_dispatch:


permissions: read-all

jobs:
  job_schedule:
    uses: ./.github/workflows/testing-triggers.yml
    with:
        test: "a workflow call"